import type { AppData } from "@/types";

export const initialData: AppData = {
  users: [
    {
      id: "vendor-1",
      email: "owner@example.com",
      password: "demo123",
      role: "vendor",
      name: "Maria Novak",
      phone: "+421 900 123 456",
      city: "Bratislava",
      bio: "Looking to sell my apartment in the city center.",
      profileComplete: true,
      createdAt: "2026-01-10T10:00:00.000Z",
    },
    {
      id: "agency-1",
      email: "agency@example.com",
      password: "demo123",
      role: "agency",
      name: "Peter Horvath",
      companyName: "Horizon Real Estate",
      licenseNumber: "RE-2024-001",
      city: "Bratislava",
      bio: "Full-service agency specializing in residential sales.",
      profileComplete: true,
      createdAt: "2026-01-08T10:00:00.000Z",
    },
  ],
  requests: [
    {
      id: "req-1",
      vendorId: "vendor-1",
      vendorName: "Maria Novak",
      title: "3-room apartment in Old Town",
      description:
        "Bright 78 m² apartment, renovated kitchen, balcony with castle view. Ready to sell within 3 months.",
      city: "Bratislava",
      propertyType: "apartment",
      price: 285000,
      bedrooms: 3,
      area: 78,
      status: "open",
      createdAt: "2026-02-15T09:00:00.000Z",
    },
    {
      id: "req-2",
      vendorId: "vendor-2",
      vendorName: "Jan Kral",
      title: "Family house with garden",
      description:
        "Detached house in quiet neighborhood, 150 m² living space, garage, large garden. Flexible on timing.",
      city: "Kosice",
      propertyType: "house",
      price: 320000,
      bedrooms: 4,
      area: 150,
      status: "open",
      createdAt: "2026-02-20T14:00:00.000Z",
    },
    {
      id: "req-3",
      vendorId: "vendor-3",
      vendorName: "Eva Simonova",
      title: "Commercial space near main square",
      description:
        "Ground-floor retail unit, high foot traffic, currently tenanted. Ideal for investors.",
      city: "Bratislava",
      propertyType: "commercial",
      price: 450000,
      area: 120,
      status: "open",
      createdAt: "2026-03-01T11:00:00.000Z",
    },
  ],
  agencyListings: [
    {
      id: "listing-1",
      agencyId: "agency-1",
      agencyName: "Horizon Real Estate",
      title: "Modern loft near Danube",
      description: "Stylish loft with river views, recently renovated.",
      city: "Bratislava",
      propertyType: "apartment",
      price: 220000,
      bedrooms: 2,
      area: 65,
      createdAt: "2026-02-10T10:00:00.000Z",
    },
  ],
  threads: [],
  messages: [],
};
